name: test

on:
 # schedule:
   # - cron: '0 0 * * 0'
 # push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # TODO: support macos
        # macos-10.15, macos-11.0
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
